[workspace]
[package]
version = "1.1.0"
name = "epoch-change-program"
edition = "2021"
license = "Apache-2.0"

[profile.release]
codegen-units = 1
lto = "fat"

[dependencies]
aptos-lc-core = { path = "../../../core", package = "aptos-lc-core", default-features = false }
risc0-zkvm = { version = "2.3.1", features = ["std", "unstable"] }

[patch.crates-io]
bls12_381 = { git = "https://github.com/risc0/zkcrypto-bls12_381.git", tag = "bls12_381/v0.8.0-risczero.1" }
sha2_0_10_9 = { package = "sha2", git = "https://github.com/risc0/RustCrypto-hashes", tag = "sha2-v0.10.9-risczero.0" }
sha2_0_9_9 = { package = "sha2", git = "https://github.com/risc0/RustCrypto-hashes", tag = "sha2-v0.9.9-risczero.0" }
tiny-keccak = { git = "https://github.com/risc0/tiny-keccak", tag = "tiny-keccak/v2.0.2-risczero.0" }
